services:
  db:
    image: mysql:8
    container_name: deview-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql-files
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
